

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="eventId")]
    public partial class AspnetWebEventEvent 
    {
        private string eventId; // pk 

        private string applicationPath;

        private string applicationVirtualPath;

        private string details;

        private int eventCode;

        private int eventDetailCode;

        private long eventOccurrence;

        private long eventSequence;

        private DateTime eventTime;

        private DateTime eventTimeUtc;

        private string eventType;

        private string exceptionType;

        private string machineName;

        private string message;

        private string requestUrl;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class AspnetWebEventEvent 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public AspnetWebEventEvent() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("eventId")]
        public string EventId
        {
            get { return eventId; }
            set { this.eventId = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("applicationPath")]
        public string ApplicationPath
        {
            get { return applicationPath; }
            set { this.applicationPath = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("applicationVirtualPath")]
        public string ApplicationVirtualPath
        {
            get { return applicationVirtualPath; }
            set { this.applicationVirtualPath = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("details")]
        public string Details
        {
            get { return details; }
            set { this.details = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("eventCode")]
        public int EventCode
        {
            get { return eventCode; }
            set { this.eventCode = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("eventDetailCode")]
        public int EventDetailCode
        {
            get { return eventDetailCode; }
            set { this.eventDetailCode = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("eventOccurrence")]
        public long EventOccurrence
        {
            get { return eventOccurrence; }
            set { this.eventOccurrence = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("eventSequence")]
        public long EventSequence
        {
            get { return eventSequence; }
            set { this.eventSequence = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("eventTime")]
        public DateTime EventTime
        {
            get { return eventTime; }
            set { this.eventTime = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("eventTimeUtc")]
        public DateTime EventTimeUtc
        {
            get { return eventTimeUtc; }
            set { this.eventTimeUtc = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("eventType")]
        public string EventType
        {
            get { return eventType; }
            set { this.eventType = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("exceptionType")]
        public string ExceptionType
        {
            get { return exceptionType; }
            set { this.exceptionType = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("machineName")]
        public string MachineName
        {
            get { return machineName; }
            set { this.machineName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("message")]
        public string Message
        {
            get { return message; }
            set { this.message = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("requestUrl")]
        public string RequestUrl
        {
            get { return requestUrl; }
            set { this.requestUrl = value; }
        }
 

    }
}
*/
#endregion //main class file contents
