

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="authID")]
    public partial class TAuthRoleBased 
    {
        private int authID; // pk 

        private string authKey;

        private IList<TModuleDef> tAuthRoleModuleDef = new List<TModuleDef>(); 


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TAuthRoleBased 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TAuthRoleBased() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("authID")]
        public int AuthID
        {
            get { return authID; }
            set { this.authID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("authKey")]
        public string AuthKey
        {
            get { return authKey; }
            set { this.authKey = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tAuthRoleModuleDef")]
        public IList<TModuleDef> TAuthRoleModuleDefs
        {
            get { return tAuthRoleModuleDef; }
        }
 

    }
}
*/
#endregion //main class file contents
