

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="id")]
    public partial class TBannedIpAddress 
    {
        private int id; // pk 

        private string comment;

        private DateTime createdOn;

        private string ipAddress;

        private DateTime? updatedOn;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TBannedIpAddress 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TBannedIpAddress() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("comment")]
        public string Comment
        {
            get { return comment; }
            set { this.comment = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("createdOn")]
        public DateTime CreatedOn
        {
            get { return createdOn; }
            set { this.createdOn = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("ipAddress")]
        public string IpAddress
        {
            get { return ipAddress; }
            set { this.ipAddress = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("updatedOn")]
        public DateTime? UpdatedOn
        {
            get { return updatedOn; }
            set { this.updatedOn = value; }
        }
 

    }
}
*/
#endregion //main class file contents
