

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="id")]
    public partial class TBannedIpNetwork 
    {
        private int id; // pk 

        private string comment;

        private DateTime createdOn;

        private string endIpAddress;

        private string ipException;

        private string startIpAddress;

        private DateTime? updatedOn;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TBannedIpNetwork 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TBannedIpNetwork() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("comment")]
        public string Comment
        {
            get { return comment; }
            set { this.comment = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("createdOn")]
        public DateTime CreatedOn
        {
            get { return createdOn; }
            set { this.createdOn = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("endIpAddress")]
        public string EndIpAddress
        {
            get { return endIpAddress; }
            set { this.endIpAddress = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("ipException")]
        public string IpException
        {
            get { return ipException; }
            set { this.ipException = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("startIpAddress")]
        public string StartIpAddress
        {
            get { return startIpAddress; }
            set { this.startIpAddress = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("updatedOn")]
        public DateTime? UpdatedOn
        {
            get { return updatedOn; }
            set { this.updatedOn = value; }
        }
 

    }
}
*/
#endregion //main class file contents
