using System;
using System.Collections.Generic;

namespace PayaDB
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files (x86)\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialuserdefault.vm
    // NOTE: Field declarations and 'Object ID' class implementation are added to the 'designer' file.
    //       Changes made to the 'designer' file will be overwritten by the wizard.  	
    public partial class TContent
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TContent()
        {
        }

        [Telerik.OpenAccess.FieldAlias("contentID")]
        public int ContentID
        {
            get { return contentID; }
            set { this.contentID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("approved")]
        public bool Approved
        {
            get { return approved; }
            set { this.approved = value; }
        }

        [Telerik.OpenAccess.FieldAlias("body")]
        public string Body
        {
            get { return body; }
            set { this.body = value; }
        }

        [Telerik.OpenAccess.FieldAlias("cOrder")]
        public int? COrder
        {
            get { return cOrder; }
            set { this.cOrder = value; }
        }

        [Telerik.OpenAccess.FieldAlias("creationDate")]
        public DateTime CreationDate
        {
            get { return creationDate; }
            set { this.creationDate = value; }
        }

        [Telerik.OpenAccess.FieldAlias("creatorID")]
        public int CreatorID
        {
            get { return creatorID; }
            set { this.creatorID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("daysOfWeek")]
        public string DaysOfWeek
        {
            get { return daysOfWeek; }
            set { this.daysOfWeek = value; }
        }

        [Telerik.OpenAccess.FieldAlias("endDate")]
        public DateTime? EndDate
        {
            get { return endDate; }
            set { this.endDate = value; }
        }

        [Telerik.OpenAccess.FieldAlias("isAlwaysShow")]
        public bool IsAlwaysShow
        {
            get { return isAlwaysShow; }
            set { this.isAlwaysShow = value; }
        }

        [Telerik.OpenAccess.FieldAlias("moduleID")]
        public int ModuleID
        {
            get { return moduleID; }
            set { this.moduleID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("startDate")]
        public DateTime? StartDate
        {
            get { return startDate; }
            set { this.startDate = value; }
        }

        [Telerik.OpenAccess.FieldAlias("title")]
        public string Title
        {
            get { return title; }
            set { this.title = value; }
        }

        [Telerik.OpenAccess.FieldAlias("tModule")]
        public TModule TModule
        {
            get { return tModule; }
            set { this.tModule = value; }
        }


    }
}
