

using System;
using System.Collections.Generic;

namespace PayaDB
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files (x86)\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField = "contentID")]
    public partial class TContent
    {
        private int contentID; // pk 

        private bool approved;

        private string body;

        private int? cOrder;

        private DateTime creationDate;

        private int creatorID;

        private string daysOfWeek;

        private DateTime? endDate;

        private bool isAlwaysShow;

        private int moduleID;

        private DateTime? startDate;

        private string title;

        private TModule tModule;





    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TContent 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TContent() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("contentID")]
        public int ContentID
        {
            get { return contentID; }
            set { this.contentID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("approved")]
        public bool Approved
        {
            get { return approved; }
            set { this.approved = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("body")]
        public string Body
        {
            get { return body; }
            set { this.body = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("cOrder")]
        public int? COrder
        {
            get { return cOrder; }
            set { this.cOrder = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("creationDate")]
        public DateTime CreationDate
        {
            get { return creationDate; }
            set { this.creationDate = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("creatorID")]
        public int CreatorID
        {
            get { return creatorID; }
            set { this.creatorID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("daysOfWeek")]
        public string DaysOfWeek
        {
            get { return daysOfWeek; }
            set { this.daysOfWeek = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("endDate")]
        public DateTime? EndDate
        {
            get { return endDate; }
            set { this.endDate = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("isAlwaysShow")]
        public bool IsAlwaysShow
        {
            get { return isAlwaysShow; }
            set { this.isAlwaysShow = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("moduleID")]
        public int ModuleID
        {
            get { return moduleID; }
            set { this.moduleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("startDate")]
        public DateTime? StartDate
        {
            get { return startDate; }
            set { this.startDate = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("title")]
        public string Title
        {
            get { return title; }
            set { this.title = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tModule")]
        public TModule TModule
        {
            get { return tModule; }
            set { this.tModule = value; }
        }
 

    }
}
*/
#endregion //main class file contents
