

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="id")]
    public partial class TForgetPass 
    {
        private int id; // pk 

        private DateTime dateSent;

        private Guid reqGUID;

        private int userID;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TForgetPass 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TForgetPass() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("dateSent")]
        public DateTime DateSent
        {
            get { return dateSent; }
            set { this.dateSent = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("reqGUID")]
        public Guid ReqGUID
        {
            get { return reqGUID; }
            set { this.reqGUID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("userID")]
        public int UserID
        {
            get { return userID; }
            set { this.userID = value; }
        }
 

    }
}
*/
#endregion //main class file contents
