

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="languageID")]
    public partial class TLanguage 
    {
        private int languageID; // pk 

        private string calendarLanguage;

        private string culture;

        private bool direction;

        private bool enabled;

        private string homeTabName;

        private string languageName;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TLanguage 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TLanguage() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("languageID")]
        public int LanguageID
        {
            get { return languageID; }
            set { this.languageID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("calendarLanguage")]
        public string CalendarLanguage
        {
            get { return calendarLanguage; }
            set { this.calendarLanguage = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("culture")]
        public string Culture
        {
            get { return culture; }
            set { this.culture = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("direction")]
        public bool Direction
        {
            get { return direction; }
            set { this.direction = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("enabled")]
        public bool Enabled
        {
            get { return enabled; }
            set { this.enabled = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("homeTabName")]
        public string HomeTabName
        {
            get { return homeTabName; }
            set { this.homeTabName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("languageName")]
        public string LanguageName
        {
            get { return languageName; }
            set { this.languageName = value; }
        }
 

    }
}
*/
#endregion //main class file contents
