

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="id")]
    public partial class TLocalResource 
    {
        private int id; // pk 

        private int languageID;

        private string resourceName;

        private string resourceValue;

        private TLanguage tLanguage;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TLocalResource 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TLocalResource() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("languageID")]
        public int LanguageID
        {
            get { return languageID; }
            set { this.languageID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("resourceName")]
        public string ResourceName
        {
            get { return resourceName; }
            set { this.resourceName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("resourceValue")]
        public string ResourceValue
        {
            get { return resourceValue; }
            set { this.resourceValue = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tLanguage")]
        public TLanguage TLanguage
        {
            get { return tLanguage; }
            set { this.tLanguage = value; }
        }
 

    }
}
*/
#endregion //main class file contents
