

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="moduleDefID")]
    public partial class TModuleDef 
    {
        private int moduleDefID; // pk 

        private bool? adminType;

        private string deskTopSRC;

        private bool enabled;

        private string moduleKey;

        private bool updatable;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TModuleDef 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TModuleDef() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("moduleDefID")]
        public int ModuleDefID
        {
            get { return moduleDefID; }
            set { this.moduleDefID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("adminType")]
        public bool? AdminType
        {
            get { return adminType; }
            set { this.adminType = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("deskTopSRC")]
        public string DeskTopSRC
        {
            get { return deskTopSRC; }
            set { this.deskTopSRC = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("enabled")]
        public bool Enabled
        {
            get { return enabled; }
            set { this.enabled = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("moduleKey")]
        public string ModuleKey
        {
            get { return moduleKey; }
            set { this.moduleKey = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("updatable")]
        public bool Updatable
        {
            get { return updatable; }
            set { this.updatable = value; }
        }
 

    }
}
*/
#endregion //main class file contents
