

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="mSettID")]
    public partial class TModuleSetting 
    {
        private int mSettID; // pk 

        private int moduleID;

        private int settingID;

        private string settingValue;

        private TModule tModule;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TModuleSetting 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TModuleSetting() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("mSettID")]
        public int MSettID
        {
            get { return mSettID; }
            set { this.mSettID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("moduleID")]
        public int ModuleID
        {
            get { return moduleID; }
            set { this.moduleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("settingID")]
        public int SettingID
        {
            get { return settingID; }
            set { this.settingID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("settingValue")]
        public string SettingValue
        {
            get { return settingValue; }
            set { this.settingValue = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tModule")]
        public TModule TModule
        {
            get { return tModule; }
            set { this.tModule = value; }
        }
 

    }
}
*/
#endregion //main class file contents
