

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="moduleRoleID")]
    public partial class TModuleRole 
    {
        private int moduleRoleID; // pk 

        private int authID;

        private int moduleID;

        private int roleID;

        private TAuthRoleBased tAuthRoleBased;

        private TModule tModule;

        private TRole tRole;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TModuleRole 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TModuleRole() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("moduleRoleID")]
        public int ModuleRoleID
        {
            get { return moduleRoleID; }
            set { this.moduleRoleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("authID")]
        public int AuthID
        {
            get { return authID; }
            set { this.authID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("moduleID")]
        public int ModuleID
        {
            get { return moduleID; }
            set { this.moduleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("roleID")]
        public int RoleID
        {
            get { return roleID; }
            set { this.roleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tAuthRoleBased")]
        public TAuthRoleBased TAuthRoleBased
        {
            get { return tAuthRoleBased; }
            set { this.tAuthRoleBased = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tModule")]
        public TModule TModule
        {
            get { return tModule; }
            set { this.tModule = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tRole")]
        public TRole TRole
        {
            get { return tRole; }
            set { this.tRole = value; }
        }
 

    }
}
*/
#endregion //main class file contents
