

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="monID")]
    public partial class TMonitoring 
    {
        private int monID; // pk 

        private DateTime? activityTime;

        private string activityType;

        private bool? browserIsAOL;

        private string browserName;

        private string browserPlatform;

        private string browserType;

        private string browserVersion;

        private int? pageID;

        private int? portalID;

        private string referrer;

        private string sessionID;

        private string userAgent;

        private string userHostAddress;

        private int? userID;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TMonitoring 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TMonitoring() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("monID")]
        public int MonID
        {
            get { return monID; }
            set { this.monID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("activityTime")]
        public DateTime? ActivityTime
        {
            get { return activityTime; }
            set { this.activityTime = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("activityType")]
        public string ActivityType
        {
            get { return activityType; }
            set { this.activityType = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("browserIsAOL")]
        public bool? BrowserIsAOL
        {
            get { return browserIsAOL; }
            set { this.browserIsAOL = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("browserName")]
        public string BrowserName
        {
            get { return browserName; }
            set { this.browserName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("browserPlatform")]
        public string BrowserPlatform
        {
            get { return browserPlatform; }
            set { this.browserPlatform = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("browserType")]
        public string BrowserType
        {
            get { return browserType; }
            set { this.browserType = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("browserVersion")]
        public string BrowserVersion
        {
            get { return browserVersion; }
            set { this.browserVersion = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("pageID")]
        public int? PageID
        {
            get { return pageID; }
            set { this.pageID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("portalID")]
        public int? PortalID
        {
            get { return portalID; }
            set { this.portalID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("referrer")]
        public string Referrer
        {
            get { return referrer; }
            set { this.referrer = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("sessionID")]
        public string SessionID
        {
            get { return sessionID; }
            set { this.sessionID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("userAgent")]
        public string UserAgent
        {
            get { return userAgent; }
            set { this.userAgent = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("userHostAddress")]
        public string UserHostAddress
        {
            get { return userHostAddress; }
            set { this.userHostAddress = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("userID")]
        public int? UserID
        {
            get { return userID; }
            set { this.userID = value; }
        }
 

    }
}
*/
#endregion //main class file contents
