

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="objRoleID")]
    public partial class TObjRole 
    {
        private int objRoleID; // pk 

        private int authID;

        private int moduleID;

        private int objID;

        private int roleID;

        private TAuthObjBased tAuthObjBased;

        private TModule tModule;

        private TRole tRole;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TObjRole 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TObjRole() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("objRoleID")]
        public int ObjRoleID
        {
            get { return objRoleID; }
            set { this.objRoleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("authID")]
        public int AuthID
        {
            get { return authID; }
            set { this.authID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("moduleID")]
        public int ModuleID
        {
            get { return moduleID; }
            set { this.moduleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("objID")]
        public int ObjID
        {
            get { return objID; }
            set { this.objID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("roleID")]
        public int RoleID
        {
            get { return roleID; }
            set { this.roleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tAuthObjBased")]
        public TAuthObjBased TAuthObjBased
        {
            get { return tAuthObjBased; }
            set { this.tAuthObjBased = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tModule")]
        public TModule TModule
        {
            get { return tModule; }
            set { this.tModule = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tRole")]
        public TRole TRole
        {
            get { return tRole; }
            set { this.tRole = value; }
        }
 

    }
}
*/
#endregion //main class file contents
