

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="objUserID")]
    public partial class TObjUser 
    {
        private int objUserID; // pk 

        private int authID;

        private int moduleID;

        private int objID;

        private int userID;

        private TAuthObjBased tAuthObjBased;

        private TModule tModule;

        private TUser tUser;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TObjUser 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TObjUser() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("objUserID")]
        public int ObjUserID
        {
            get { return objUserID; }
            set { this.objUserID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("authID")]
        public int AuthID
        {
            get { return authID; }
            set { this.authID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("moduleID")]
        public int ModuleID
        {
            get { return moduleID; }
            set { this.moduleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("objID")]
        public int ObjID
        {
            get { return objID; }
            set { this.objID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("userID")]
        public int UserID
        {
            get { return userID; }
            set { this.userID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tAuthObjBased")]
        public TAuthObjBased TAuthObjBased
        {
            get { return tAuthObjBased; }
            set { this.tAuthObjBased = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tModule")]
        public TModule TModule
        {
            get { return tModule; }
            set { this.tModule = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tUser")]
        public TUser TUser
        {
            get { return tUser; }
            set { this.tUser = value; }
        }
 

    }
}
*/
#endregion //main class file contents
