

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="id")]
    public partial class TPortalLanguage 
    {
        private int id; // pk 

        private bool enabled;

        private int homeTabID;

        private int languageID;

        private int portalID;

        private TLanguage tLanguage;

        private TPortal tPortal;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TPortalLanguage 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TPortalLanguage() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("enabled")]
        public bool Enabled
        {
            get { return enabled; }
            set { this.enabled = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("homeTabID")]
        public int HomeTabID
        {
            get { return homeTabID; }
            set { this.homeTabID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("languageID")]
        public int LanguageID
        {
            get { return languageID; }
            set { this.languageID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("portalID")]
        public int PortalID
        {
            get { return portalID; }
            set { this.portalID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tLanguage")]
        public TLanguage TLanguage
        {
            get { return tLanguage; }
            set { this.tLanguage = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tPortal")]
        public TPortal TPortal
        {
            get { return tPortal; }
            set { this.tPortal = value; }
        }
 

    }
}
*/
#endregion //main class file contents
