

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="portalID")]
    public partial class TPortal 
    {
        private int portalID; // pk 

        private string portalAlias;

        private string portalName;

        private string portalPath;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TPortal 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TPortal() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("portalID")]
        public int PortalID
        {
            get { return portalID; }
            set { this.portalID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("portalAlias")]
        public string PortalAlias
        {
            get { return portalAlias; }
            set { this.portalAlias = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("portalName")]
        public string PortalName
        {
            get { return portalName; }
            set { this.portalName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("portalPath")]
        public string PortalPath
        {
            get { return portalPath; }
            set { this.portalPath = value; }
        }
 

    }
}
*/
#endregion //main class file contents
