

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(Identity=typeof(PayaDB.TPortalSetting.ID))]
    public partial class TPortalSetting 
    {
        private int portalID; // pk 

        private string settingName; // pk 

        private string settingValue;

        private TPortal tPortal;


        #region Object ID class
        // Application identity objectid-class.
        // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\objectid\default.vm
        public class ID : Telerik.OpenAccess.IObjectId 
        {
            public int portalID; //pk

            public string settingName; //pk


            public ID() 
            {
            }

            public ID(string s) 
            {
                int i, p = 0;
                i = s.IndexOf('-', p);
                portalID = System.Int32.Parse(s.Substring(p, i-p));
                p = i + 1;
                i = s.IndexOf('-', p);
                settingName = s.Substring(p);

            }

            public override bool Equals(object o) 
            {
                if (this == o) return true;
                if (!(o is TPortalSetting.ID)) return false;

                TPortalSetting.ID id = (TPortalSetting.ID) o;

                if(this.portalID != id.portalID) return false;

                if(this.settingName != id.settingName) return false;

                return true;
            }

            public override int GetHashCode() 
            {
                int result = 0;
                result = 29 * result + portalID.GetHashCode();
                result = 29 * result + settingName.GetHashCode();

                return result;
            }

            public override string ToString() 
            {
                System.Text.StringBuilder buffer = new System.Text.StringBuilder();

                buffer.Append(portalID).Append('-');

                buffer.Append(settingName);

                return buffer.ToString();
            }
        }

        #endregion //Object ID class
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TPortalSetting 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TPortalSetting() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("portalID")]
        public int PortalID
        {
            get { return portalID; }
            set { this.portalID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("settingName")]
        public string SettingName
        {
            get { return settingName; }
            set { this.settingName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("settingValue")]
        public string SettingValue
        {
            get { return settingValue; }
            set { this.settingValue = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tPortal")]
        public TPortal TPortal
        {
            get { return tPortal; }
            set { this.tPortal = value; }
        }
 

    }
}
*/
#endregion //main class file contents
