

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="reqID")]
    public partial class TRegisterReq 
    {
        private int reqID; // pk 

        private string email;

        private string firstName;

        private string lastName;

        private string phoneNo;

        private int portalID;

        private string userName;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TRegisterReq 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TRegisterReq() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("reqID")]
        public int ReqID
        {
            get { return reqID; }
            set { this.reqID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("email")]
        public string Email
        {
            get { return email; }
            set { this.email = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("firstName")]
        public string FirstName
        {
            get { return firstName; }
            set { this.firstName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("lastName")]
        public string LastName
        {
            get { return lastName; }
            set { this.lastName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("phoneNo")]
        public string PhoneNo
        {
            get { return phoneNo; }
            set { this.phoneNo = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("portalID")]
        public int PortalID
        {
            get { return portalID; }
            set { this.portalID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("userName")]
        public string UserName
        {
            get { return userName; }
            set { this.userName = value; }
        }
 

    }
}
*/
#endregion //main class file contents
