

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="roleID")]
    public partial class TRole 
    {
        private int roleID; // pk 

        private int? portalID;

        private string roleKey;

        private TPortal tPortal;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TRole 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TRole() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("roleID")]
        public int RoleID
        {
            get { return roleID; }
            set { this.roleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("portalID")]
        public int? PortalID
        {
            get { return portalID; }
            set { this.portalID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("roleKey")]
        public string RoleKey
        {
            get { return roleKey; }
            set { this.roleKey = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tPortal")]
        public TPortal TPortal
        {
            get { return tPortal; }
            set { this.tPortal = value; }
        }
 

    }
}
*/
#endregion //main class file contents
