

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="tabRoleID")]
    public partial class TTabRole 
    {
        private int tabRoleID; // pk 

        private int roleID;

        private int tabID;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TTabRole 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TTabRole() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("tabRoleID")]
        public int TabRoleID
        {
            get { return tabRoleID; }
            set { this.tabRoleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("roleID")]
        public int RoleID
        {
            get { return roleID; }
            set { this.roleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tabID")]
        public int TabID
        {
            get { return tabID; }
            set { this.tabID = value; }
        }
 

    }
}
*/
#endregion //main class file contents
