

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="id")]
    public partial class TTabFlat 
    {
        private int id; // pk 

        private int? nestLevel;

        private int? tabID;

        private TTab tTab;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TTabFlat 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TTabFlat() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("nestLevel")]
        public int? NestLevel
        {
            get { return nestLevel; }
            set { this.nestLevel = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tabID")]
        public int? TabID
        {
            get { return tabID; }
            set { this.tabID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tTab")]
        public TTab TTab
        {
            get { return tTab; }
            set { this.tTab = value; }
        }
 

    }
}
*/
#endregion //main class file contents
