

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="tabID")]
    public partial class TTab 
    {
        private int tabID; // pk 

        private string description;

        private sbyte isreserved;

        private string keywords;

        private int languageID;

        private int? parentID;

        private int? portalID;

        private string roles;

        private string settings;

        private bool showFooter;

        private bool showHorizontal;

        private bool showVertical;

        private string tabName;

        private int? tabOrder;

        private sbyte target;

        private string url;

        private TLanguage tLanguage;

        private TPortal tPortal;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TTab 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TTab() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("tabID")]
        public int TabID
        {
            get { return tabID; }
            set { this.tabID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("description")]
        public string Description
        {
            get { return description; }
            set { this.description = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("isreserved")]
        public sbyte Isreserved
        {
            get { return isreserved; }
            set { this.isreserved = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("keywords")]
        public string Keywords
        {
            get { return keywords; }
            set { this.keywords = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("languageID")]
        public int LanguageID
        {
            get { return languageID; }
            set { this.languageID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("parentID")]
        public int? ParentID
        {
            get { return parentID; }
            set { this.parentID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("portalID")]
        public int PortalID
        {
            get { return portalID; }
            set { this.portalID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("roles")]
        public string Roles
        {
            get { return roles; }
            set { this.roles = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("settings")]
        public string Settings
        {
            get { return settings; }
            set { this.settings = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("showFooter")]
        public bool ShowFooter
        {
            get { return showFooter; }
            set { this.showFooter = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("showHorizontal")]
        public bool ShowHorizontal
        {
            get { return showHorizontal; }
            set { this.showHorizontal = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("showVertical")]
        public bool ShowVertical
        {
            get { return showVertical; }
            set { this.showVertical = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tabName")]
        public string TabName
        {
            get { return tabName; }
            set { this.tabName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tabOrder")]
        public int? TabOrder
        {
            get { return tabOrder; }
            set { this.tabOrder = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("target")]
        public sbyte Target
        {
            get { return target; }
            set { this.target = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("url")]
        public string Url
        {
            get { return url; }
            set { this.url = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tLanguage")]
        public TLanguage TLanguage
        {
            get { return tLanguage; }
            set { this.tLanguage = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("tPortal")]
        public TPortal TPortal
        {
            get { return tPortal; }
            set { this.tPortal = value; }
        }
 

    }
}
*/
#endregion //main class file contents
