using System;
using System.Collections.Generic;

namespace PayaDB
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files (x86)\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialuserdefault.vm
    // NOTE: Field declarations and 'Object ID' class implementation are added to the 'designer' file.
    //       Changes made to the 'designer' file will be overwritten by the wizard.  	
    public partial class TTabFlat
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TTabFlat()
        {
        }

        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }

        [Telerik.OpenAccess.FieldAlias("nestLevel")]
        public int? NestLevel
        {
            get { return nestLevel; }
            set { this.nestLevel = value; }
        }

        [Telerik.OpenAccess.FieldAlias("tabID")]
        public int? TabID
        {
            get { return tabID; }
            set { this.tabID = value; }
        }

        [Telerik.OpenAccess.FieldAlias("tTab")]
        public TTab TTab
        {
            get { return tTab; }
            set { this.tTab = value; }
        }


    }
}
