

using System;
using System.Collections.Generic;

namespace PayaDB 
{
    // Generated by Telerik OpenAccess
    // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
    [Telerik.OpenAccess.Persistent(IdentityField="userRoleID")]
    public partial class TUserRole 
    {
        private int userRoleID; // pk 

        private int roleID;

        private int userID;


        

        
    }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace PayaDB 
{
    //Generated by Telerik OpenAccess
    public partial class TUserRole 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public TUserRole() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("userRoleID")]
        public int UserRoleID
        {
            get { return userRoleID; }
            set { this.userRoleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("roleID")]
        public int RoleID
        {
            get { return roleID; }
            set { this.roleID = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("userID")]
        public int UserID
        {
            get { return userID; }
            set { this.userID = value; }
        }
 

    }
}
*/
#endregion //main class file contents
