//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Contents", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن محتوا.
        /// </summary>
        internal static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمايش همگي.
        /// </summary>
        internal static string AllView {
            get {
                return ResourceManager.GetString("AllView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاييد شده.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید محتوا.
        /// </summary>
        internal static string ApprovedContent {
            get {
                return ResourceManager.GetString("ApprovedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب همگی.
        /// </summary>
        internal static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب نحوه نمایش.
        /// </summary>
        internal static string ChooseWhenShown {
            get {
                return ResourceManager.GetString("ChooseWhenShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين محتوا  حذف خواهند شد! آيا مطمئن هستيد؟.
        /// </summary>
        internal static string ConfirmDeleteConfirm {
            get {
                return ResourceManager.GetString("ConfirmDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چند محتواي انتخاب شده حذف خواهند شد! آيا مطمئن هستيد؟.
        /// </summary>
        internal static string ConfirmDeleteContents {
            get {
                return ResourceManager.GetString("ConfirmDeleteContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوا.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت  محتوا ها - برنامه: .
        /// </summary>
        internal static string ContentManagmnet {
            get {
                return ResourceManager.GetString("ContentManagmnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايجاد کننده.
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت محتوا.
        /// </summary>
        internal static string DataManagment {
            get {
                return ResourceManager.GetString("DataManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ آخرین تغییر.
        /// </summary>
        internal static string DateCreate {
            get {
                return ResourceManager.GetString("DateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ پايان نمايش.
        /// </summary>
        internal static string DateEndView {
            get {
                return ResourceManager.GetString("DateEndView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ شروع نمايش.
        /// </summary>
        internal static string DateStartView {
            get {
                return ResourceManager.GetString("DateStartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف محتوا.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف چند محتواي انتخاب شده.
        /// </summary>
        internal static string DeleteContent {
            get {
                return ResourceManager.GetString("DeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئيات محتوا.
        /// </summary>
        internal static string DetailsContent {
            get {
                return ResourceManager.GetString("DetailsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاييد نشده.
        /// </summary>
        internal static string DontApply {
            get {
                return ResourceManager.GetString("DontApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويرايش محتوا.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويرايش محتوا.
        /// </summary>
        internal static string EditContent {
            get {
                return ResourceManager.GetString("EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اين محتوا وجود ندارد.
        /// </summary>
        internal static string ErrorDeleteContent {
            get {
                return ResourceManager.GetString("ErrorDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين محتوا تاييد نشده است..
        /// </summary>
        internal static string ErrorDontApplyContent {
            get {
                return ResourceManager.GetString("ErrorDontApplyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ويرايش اين اطلاعات وجود ندارد. احتمالا تاريخهاي مربوط به آن را درست وارد نکرده ايد. لطفا دوباره سعي کنيد.
        /// </summary>
        internal static string ErrorEditContentDate {
            get {
                return ResourceManager.GetString("ErrorEditContentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت اين محتوا وجود ندارد. احتمالا تاريخهاي مربوط به آن را درست وارد نکرده ايد. لطفا دوباره سعي کنيد.
        /// </summary>
        internal static string ErrorInsertContent {
            get {
                return ResourceManager.GetString("ErrorInsertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت اين محتوا وجود ندارد. احتمالا تاريخهاي مربوط به آن را درست وارد نکرده ايد. لطفا دوباره سعي کنيد..
        /// </summary>
        internal static string ErrorInsertContentDate {
            get {
                return ResourceManager.GetString("ErrorInsertContentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        internal static string friday {
            get {
                return ResourceManager.GetString("friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات.
        /// </summary>
        internal static string InsertData {
            get {
                return ResourceManager.GetString("InsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین به روزرسانی.
        /// </summary>
        internal static string LastDateUpdate {
            get {
                return ResourceManager.GetString("LastDateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين محتوا تاييد شده است و در سامانه نمايش داده مي شود..
        /// </summary>
        internal static string MessageApplyContent {
            get {
                return ResourceManager.GetString("MessageApplyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مورد نظر شما با موفقيت ثبت گرديد.
        /// </summary>
        internal static string MessageInsertContent {
            get {
                return ResourceManager.GetString("MessageInsertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مورد نظر شما با موفقيت ويرايش گرديد..
        /// </summary>
        internal static string MessageUpdateContent {
            get {
                return ResourceManager.GetString("MessageUpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه .
        /// </summary>
        internal static string monday {
            get {
                return ResourceManager.GetString("monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتواي جديد.
        /// </summary>
        internal static string NewContent {
            get {
                return ResourceManager.GetString("NewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام موارد اختياري مي باشند.
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب نمايش.
        /// </summary>
        internal static string orderShow {
            get {
                return ResourceManager.GetString("orderShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رديف
        ///.
        /// </summary>
        internal static string RowId {
            get {
                return ResourceManager.GetString("RowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه .
        /// </summary>
        internal static string saturday {
            get {
                return ResourceManager.GetString("saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش همیشگی.
        /// </summary>
        internal static string ShowContentAllDaye {
            get {
                return ResourceManager.GetString("ShowContentAllDaye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نمايش.
        /// </summary>
        internal static string ShowDate {
            get {
                return ResourceManager.GetString("ShowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روزهاي نمايش.
        /// </summary>
        internal static string ShowDays {
            get {
                return ResourceManager.GetString("ShowDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعيت تاييد محتوا.
        /// </summary>
        internal static string StatusApplyContent {
            get {
                return ResourceManager.GetString("StatusApplyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکشنبه .
        /// </summary>
        internal static string sunday {
            get {
                return ResourceManager.GetString("sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه شنبه .
        /// </summary>
        internal static string tuesday {
            get {
                return ResourceManager.GetString("tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنچ شنبه .
        /// </summary>
        internal static string tursday {
            get {
                return ResourceManager.GetString("tursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف همگی.
        /// </summary>
        internal static string UnCheckAll {
            get {
                return ResourceManager.GetString("UnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت تغييرات.
        /// </summary>
        internal static string UpdateData {
            get {
                return ResourceManager.GetString("UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ايجاد کننده.
        /// </summary>
        internal static string UserCreator {
            get {
                return ResourceManager.GetString("UserCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً عنوان را وارد نماييد.
        /// </summary>
        internal static string ValidationCaption {
            get {
                return ResourceManager.GetString("ValidationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عدد وارد نمایید.
        /// </summary>
        internal static string ValidationEnterNumer {
            get {
                return ResourceManager.GetString("ValidationEnterNumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ترتیب نمایش را وارد نمایید.
        /// </summary>
        internal static string ValidationNumber {
            get {
                return ResourceManager.GetString("ValidationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to براي ثبت يا ويرايش اطلاعات، پرکردن موارد ستاره دار الزامي است..
        /// </summary>
        internal static string ValidationStar {
            get {
                return ResourceManager.GetString("ValidationStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه .
        /// </summary>
        internal static string wednsday {
            get {
                return ResourceManager.GetString("wednsday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
