//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Gallery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gallery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Gallery", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقدام.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        internal static string AddedDate {
            get {
                return ResourceManager.GetString("AddedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کردن گروه.
        /// </summary>
        internal static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن آيتم جديد.
        /// </summary>
        internal static string AddNewItem {
            get {
                return ResourceManager.GetString("AddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه شد .
        /// </summary>
        internal static string AddTo {
            get {
                return ResourceManager.GetString("AddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن فایل به دیتابیس.
        /// </summary>
        internal static string AddTodb {
            get {
                return ResourceManager.GetString("AddTodb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه گروهها.
        /// </summary>
        internal static string AllCategory {
            get {
                return ResourceManager.GetString("AllCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيتم را تاييد مي کنم. به عنوان يک آيتم رسمي در سامانه قرار گيرد..
        /// </summary>
        internal static string ApplyItem {
            get {
                return ResourceManager.GetString("ApplyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرشيو.
        /// </summary>
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروهها.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Modules/Gallery/lightbox2.02/images/closelabelF.gif.
        /// </summary>
        internal static string CloseImagePath {
            get {
                return ResourceManager.GetString("CloseImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  گروههای تعریف شده در نگارخانه به صورت لیست در اختیار شما قرار داده شده با انتخاب هر گروه ، لیست عکسهای مربوطه نمایش داده می شود.
        /// </summary>
        internal static string CommentCat {
            get {
                return ResourceManager.GetString("CommentCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی تصاویر .
        /// </summary>
        internal static string CommentSearch {
            get {
                return ResourceManager.GetString("CommentSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصاویر منتخب از مجموعه زیر گروههای این گروه.
        /// </summary>
        internal static string CommentSelectedPic {
            get {
                return ResourceManager.GetString("CommentSelectedPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين آيتم حذف خواهد شد! آيا مطمئن هستيد؟.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيتم تاييد شده.
        /// </summary>
        internal static string ConfirmItem {
            get {
                return ResourceManager.GetString("ConfirmItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفعات مشاهده.
        /// </summary>
        internal static string CountView {
            get {
                return ResourceManager.GetString("CountView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايجاد کننده .
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Modules/Gallery/lightbox2.02/css/lightboxF.css.
        /// </summary>
        internal static string CssPath {
            get {
                return ResourceManager.GetString("CssPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ ايجاد.
        /// </summary>
        internal static string DateCreate {
            get {
                return ResourceManager.GetString("DateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف گروه.
        /// </summary>
        internal static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف آیتم.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيتم را تاييد نمي کنم..
        /// </summary>
        internal static string DontApllyItem {
            get {
                return ResourceManager.GetString("DontApllyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش گروه.
        /// </summary>
        internal static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويرايش آيتم.
        /// </summary>
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کردن تصویر دچار مشکل شد ، سایز عکس طبقه بندی باید حداکثر صد در صد پيکسل باشد..
        /// </summary>
        internal static string ErrorAddCategoryImage {
            get {
                return ResourceManager.GetString("ErrorAddCategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کردن فایل دچار مشکل شد.
        /// </summary>
        internal static string ErrorAddFile {
            get {
                return ResourceManager.GetString("ErrorAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کردن تصویر دچار مشکل شد.
        /// </summary>
        internal static string ErrorAddImage {
            get {
                return ResourceManager.GetString("ErrorAddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس مورد نظر را انتخاب کنید.
        /// </summary>
        internal static string ErrorChecked {
            get {
                return ResourceManager.GetString("ErrorChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکالي در حذف گروه بوجود آمد. احتمالاً اين گروه داراي زير گروه است!.
        /// </summary>
        internal static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف گروه وجود ندارد ، احتمالا گروه دارای محصول می باشد .
        /// </summary>
        internal static string ErrorDeleteCat {
            get {
                return ResourceManager.GetString("ErrorDeleteCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف فایل وجود ندارد.
        /// </summary>
        internal static string ErrorDeleteFile {
            get {
                return ResourceManager.GetString("ErrorDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اين آيتم وجود ندارد. احتمالا براي کسي ارسال شده است..
        /// </summary>
        internal static string ErrorDeleteItem {
            get {
                return ResourceManager.GetString("ErrorDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف فایل نمونه وجود ندارد.
        /// </summary>
        internal static string ErrorDeletePic {
            get {
                return ResourceManager.GetString("ErrorDeletePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکال در ذخیره گروه ، احتمالا گروه تکراری است.
        /// </summary>
        internal static string ErrorDuplicateGroup {
            get {
                return ResourceManager.GetString("ErrorDuplicateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ويرايش آيتم وجود ندارد. احتمالا نوع فايل مجاز نمي باشد..
        /// </summary>
        internal static string ErrorEditItem {
            get {
                return ResourceManager.GetString("ErrorEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ويرايش آيتم کوچک وجود ندارد. احتمالا نوع آن مجاز نمي باشد..
        /// </summary>
        internal static string ErrorEditSmallItem {
            get {
                return ResourceManager.GetString("ErrorEditSmallItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل الحاقی بایستی فایل تصویری باشد ..
        /// </summary>
        internal static string ErrorFileType {
            get {
                return ResourceManager.GetString("ErrorFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان افزودن اين گروه وجود ندارد!.
        /// </summary>
        internal static string ErrorInsert {
            get {
                return ResourceManager.GetString("ErrorInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت آيتم وجود ندارد! احتمالا نوع آيتم مجاز نمي باشد. لطفا دوباره سعي کنيد..
        /// </summary>
        internal static string ErrorInsertItem {
            get {
                return ResourceManager.GetString("ErrorInsertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت آيتم وجود ندارد. لطفا دوباره سعي کنيد..
        /// </summary>
        internal static string ErrorInsertItemTryAgain {
            get {
                return ResourceManager.GetString("ErrorInsertItemTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت آيتم کوچک وجود ندارد. احتمالا نوع آن مجاز نمي باشد..
        /// </summary>
        internal static string ErrorInsertSmallItem {
            get {
                return ResourceManager.GetString("ErrorInsertSmallItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز عکس انتخاب شده به عنوان تصویر کوچک بزرگتر از حد مجاز می باشد.
        /// </summary>
        internal static string ErrorInsertTmbImage {
            get {
                return ResourceManager.GetString("ErrorInsertTmbImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ایجاد تصویر در گالری لطفا ابتدا لاگین کنید.
        /// </summary>
        internal static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکالي در انتقال گروه به وجود آمد!..
        /// </summary>
        internal static string ErrorMove {
            get {
                return ResourceManager.GetString("ErrorMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال تصویر به گروه دیگر با مشکل مواجه شد .
        /// </summary>
        internal static string ErrorTarnsferToGroup {
            get {
                return ResourceManager.GetString("ErrorTarnsferToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکال در ذخیره اطلاعات.
        /// </summary>
        internal static string ErrorUpdate {
            get {
                return ResourceManager.GetString("ErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست فایلها.
        /// </summary>
        internal static string FileList {
            get {
                return ResourceManager.GetString("FileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت فایل.
        /// </summary>
        internal static string FileManger {
            get {
                return ResourceManager.GetString("FileManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل.
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده فايل.
        /// </summary>
        internal static string FileView {
            get {
                return ResourceManager.GetString("FileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيلم.
        /// </summary>
        internal static string Film {
            get {
                return ResourceManager.GetString("Film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرشيو گالري تصاوير.
        /// </summary>
        internal static string GalleryImageArchive {
            get {
                return ResourceManager.GetString("GalleryImageArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرشيو گالري آيتم - برنامه .
        /// </summary>
        internal static string GalleryItemProgramArchive {
            get {
                return ResourceManager.GetString("GalleryItemProgramArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت گروههاي تصاوير.
        /// </summary>
        internal static string GroupImageManger {
            get {
                return ResourceManager.GetString("GroupImageManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت گروهها.
        /// </summary>
        internal static string GroupManagment {
            get {
                return ResourceManager.GetString("GroupManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت گروهها - برنامه.
        /// </summary>
        internal static string GroupProgramManagment {
            get {
                return ResourceManager.GetString("GroupProgramManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال عکسهای انتخاب شده به گروه :.
        /// </summary>
        internal static string GroupTransfer {
            get {
                return ResourceManager.GetString("GroupTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصوير.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری تصاویر.
        /// </summary>
        internal static string ImageGallery {
            get {
                return ResourceManager.GetString("ImageGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  مديريت تصاوير.
        /// </summary>
        internal static string ImagesManagment {
            get {
                return ResourceManager.GetString("ImagesManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ويرايش اطلاعات عمومي آيتم وجود ندارد..
        /// </summary>
        internal static string ImpossibleEditItem {
            get {
                return ResourceManager.GetString("ImpossibleEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات.
        /// </summary>
        internal static string InsertData {
            get {
                return ResourceManager.GetString("InsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عنوان گروه درج شود.
        /// </summary>
        internal static string InsertGroupName {
            get {
                return ResourceManager.GetString("InsertGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر آيتم شما فيلم يا صدا يا تصوير حجيمي است، مي توانيد براي معرفي آن يک تصوير کوچک وارد کنيد. تصوير موجود وضعيت نمايش اوليه آيتم شما را نشان مي دهد..
        /// </summary>
        internal static string IntroductionTypeFile {
            get {
                return ResourceManager.GetString("IntroductionTypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوند فایل معتبر نیست..
        /// </summary>
        internal static string Invalidextension {
            get {
                return ResourceManager.GetString("Invalidextension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  آيتم.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت آيتمها - برنامه .
        /// </summary>
        internal static string ItemProgramManagment {
            get {
                return ResourceManager.GetString("ItemProgramManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت آيتمها.
        /// </summary>
        internal static string ItemsManagment {
            get {
                return ResourceManager.GetString("ItemsManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعيت آيتم.
        /// </summary>
        internal static string ItemStatus {
            get {
                return ResourceManager.GetString("ItemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه کلیدی.
        /// </summary>
        internal static string KeyWord {
            get {
                return ResourceManager.GetString("KeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین ویرایش.
        /// </summary>
        internal static string LastWrite {
            get {
                return ResourceManager.GetString("LastWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Modules/Gallery/lightbox2.02/js/lightboxF.js.
        /// </summary>
        internal static string LightBoxF {
            get {
                return ResourceManager.GetString("LightBoxF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکان.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationEn {
            get {
                return ResourceManager.GetString("LocationEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه با موفقيت حذف شد..
        /// </summary>
        internal static string MessageDelete {
            get {
                return ResourceManager.GetString("MessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيتم مورد نظر شما با موفقيت حذف گرديد..
        /// </summary>
        internal static string MessageDeleteItem {
            get {
                return ResourceManager.GetString("MessageDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه تکراری است.
        /// </summary>
        internal static string MessageDuplicateInsert {
            get {
                return ResourceManager.GetString("MessageDuplicateInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات با موفقيت انجام شد..
        /// </summary>
        internal static string MessageInsert {
            get {
                return ResourceManager.GetString("MessageInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه با موفقيت منتقل شد..
        /// </summary>
        internal static string MessageMove {
            get {
                return ResourceManager.GetString("MessageMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال تصویر به گروه دیگر با موفقیت انجام شد .
        /// </summary>
        internal static string MessageTarnsferToGroup {
            get {
                return ResourceManager.GetString("MessageTarnsferToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويرايش اطلاعات با موفقيت انجام شد..
        /// </summary>
        internal static string MessageUpdate {
            get {
                return ResourceManager.GetString("MessageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه جديد.
        /// </summary>
        internal static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيتم جديد.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه بعد.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  آيتم تاييد نشده.
        /// </summary>
        internal static string NotConfirmItem {
            get {
                return ResourceManager.GetString("NotConfirmItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيتم برگزيده نيست..
        /// </summary>
        internal static string NotSelection {
            get {
                return ResourceManager.GetString("NotSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انجام عملیات مشکلی به وجود آمده است.
        /// </summary>
        internal static string NotSucceed {
            get {
                return ResourceManager.GetString("NotSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروههای هم مجموعه.
        /// </summary>
        internal static string ParentCat {
            get {
                return ResourceManager.GetString("ParentCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرگروه.
        /// </summary>
        internal static string ParentGroup {
            get {
                return ResourceManager.GetString("ParentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکاس.
        /// </summary>
        internal static string Photographer {
            get {
                return ResourceManager.GetString("Photographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا آيتم را وارد نماييد..
        /// </summary>
        internal static string PlzInterItem {
            get {
                return ResourceManager.GetString("PlzInterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا گروه آيتم را مشخص کنيد..
        /// </summary>
        internal static string PlzSelectItemGroup {
            get {
                return ResourceManager.GetString("PlzSelectItemGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه قبل.
        /// </summary>
        internal static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریشه.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رديف.
        /// </summary>
        internal static string RowId {
            get {
                return ResourceManager.GetString("RowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً گروهي را انتخاب کنيد!.
        /// </summary>
        internal static string SelectGroup {
            get {
                return ResourceManager.GetString("SelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروهی را انتخاب کنید....
        /// </summary>
        internal static string SelectGroupWait {
            get {
                return ResourceManager.GetString("SelectGroupWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيتم برگزيده است و به عنوان آيتم نمونه در صفحه نشان داده شود..
        /// </summary>
        internal static string SelectionItem {
            get {
                return ResourceManager.GetString("SelectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيتمهاي برگزيده.
        /// </summary>
        internal static string SelectItems {
            get {
                return ResourceManager.GetString("SelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمايش همگي.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم کوچک.
        /// </summary>
        internal static string SmallItem {
            get {
                return ResourceManager.GetString("SmallItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صدا.
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منبع.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروههای زیر مجموعه.
        /// </summary>
        internal static string SubCat {
            get {
                return ResourceManager.GetString("SubCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به زیر مجموعه گروه .
        /// </summary>
        internal static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        internal static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بار.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عنوان درج شود.
        /// </summary>
        internal static string TitleIsEmpty {
            get {
                return ResourceManager.GetString("TitleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال.
        /// </summary>
        internal static string TransferToGroup {
            get {
                return ResourceManager.GetString("TransferToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال تغييرات.
        /// </summary>
        internal static string UpdateData {
            get {
                return ResourceManager.GetString("UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *براي ثبت يا ويرايش آيتم پر کردن موارد ستاره دار الزامي است..
        /// </summary>
        internal static string ValidationStar {
            get {
                return ResourceManager.GetString("ValidationStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمايش اندازه حقيقي.
        /// </summary>
        internal static string ViewImageFreeSize {
            get {
                return ResourceManager.GetString("ViewImageFreeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه تصویر.
        /// </summary>
        internal static string ViewSize {
            get {
                return ResourceManager.GetString("ViewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
