//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Mail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intranet.DeskTopModules.News.App_GlobalResources.Mail", typeof(Mail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیام.
        /// </summary>
        public static string SendMailBodyMsg {
            get {
                return ResourceManager.GetString("SendMailBodyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز خطا در حین ارسال.
        /// </summary>
        public static string SendMailFailureMessage {
            get {
                return ResourceManager.GetString("SendMailFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس صندوق الکترونيکي دوستان.
        /// </summary>
        public static string SendMailFriendMail {
            get {
                return ResourceManager.GetString("SendMailFriendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس پست الکترونیکی مقصد را وارد کنید.
        /// </summary>
        public static string SendMailFriendMailRecuiMsg {
            get {
                return ResourceManager.GetString("SendMailFriendMailRecuiMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string SendMailFrom {
            get {
                return ResourceManager.GetString("SendMailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیام.
        /// </summary>
        public static string SendMailMessageTxt {
            get {
                return ResourceManager.GetString("SendMailMessageTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این سایت هیچ تعهددی نسبت به محتوای نامه ارسالی ندارد.
        /// </summary>
        public static string SendMailNotResposibel {
            get {
                return ResourceManager.GetString("SendMailNotResposibel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string SendMailSend {
            get {
                return ResourceManager.GetString("SendMailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرستنده.
        /// </summary>
        public static string SendMailSender {
            get {
                return ResourceManager.GetString("SendMailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ارسال با موفقیت انجام شد.
        /// </summary>
        public static string SendMailSuccessMessage {
            get {
                return ResourceManager.GetString("SendMailSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس صندوق الکترونيکي شما.
        /// </summary>
        public static string SendMailYourMail {
            get {
                return ResourceManager.GetString("SendMailYourMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس وارد شده صحیح نیست.
        /// </summary>
        public static string SendMailYourMailNotValidMsg {
            get {
                return ResourceManager.GetString("SendMailYourMailNotValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس پست الکترونیکی خود را وارد کنید.
        /// </summary>
        public static string SendMailYourMailRecuiMsg {
            get {
                return ResourceManager.GetString("SendMailYourMailRecuiMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شما.
        /// </summary>
        public static string SendMailYourName {
            get {
                return ResourceManager.GetString("SendMailYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ارسال مطلب به بيش ازيک آدرس، آنها را با , از هم جدا کنيد. برای مثال.
        /// </summary>
        public static string SendToFriendMessage {
            get {
                return ResourceManager.GetString("SendToFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال به دوستان.
        /// </summary>
        public static string SendToFriends {
            get {
                return ResourceManager.GetString("SendToFriends", resourceCulture);
            }
        }
    }
}
