//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Mail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیام.
        /// </summary>
        internal static string SendMailBodyMsg {
            get {
                return ResourceManager.GetString("SendMailBodyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز خطا در حین ارسال.
        /// </summary>
        internal static string SendMailFailureMessage {
            get {
                return ResourceManager.GetString("SendMailFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس صندوق الکترونيکي دوستان.
        /// </summary>
        internal static string SendMailFriendMail {
            get {
                return ResourceManager.GetString("SendMailFriendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس پست الکترونیکی مقصد را وارد کنید.
        /// </summary>
        internal static string SendMailFriendMailRecuiMsg {
            get {
                return ResourceManager.GetString("SendMailFriendMailRecuiMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        internal static string SendMailFrom {
            get {
                return ResourceManager.GetString("SendMailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیام.
        /// </summary>
        internal static string SendMailMessageTxt {
            get {
                return ResourceManager.GetString("SendMailMessageTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این سایت هیچ تعهددی نسبت به محتوای نامه ارسالی ندارد.
        /// </summary>
        internal static string SendMailNotResposibel {
            get {
                return ResourceManager.GetString("SendMailNotResposibel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        internal static string SendMailSend {
            get {
                return ResourceManager.GetString("SendMailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرستنده.
        /// </summary>
        internal static string SendMailSender {
            get {
                return ResourceManager.GetString("SendMailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ارسال با موفقیت انجام شد.
        /// </summary>
        internal static string SendMailSuccessMessage {
            get {
                return ResourceManager.GetString("SendMailSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس صندوق الکترونيکي شما.
        /// </summary>
        internal static string SendMailYourMail {
            get {
                return ResourceManager.GetString("SendMailYourMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس وارد شده صحیح نیست.
        /// </summary>
        internal static string SendMailYourMailNotValidMsg {
            get {
                return ResourceManager.GetString("SendMailYourMailNotValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس پست الکترونیکی خود را وارد کنید.
        /// </summary>
        internal static string SendMailYourMailRecuiMsg {
            get {
                return ResourceManager.GetString("SendMailYourMailRecuiMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شما.
        /// </summary>
        internal static string SendMailYourName {
            get {
                return ResourceManager.GetString("SendMailYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ارسال مطلب به بيش ازيک آدرس، آنها را با , از هم جدا کنيد. برای مثال.
        /// </summary>
        internal static string SendToFriendMessage {
            get {
                return ResourceManager.GetString("SendToFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال به دوستان.
        /// </summary>
        internal static string SendToFriends {
            get {
                return ResourceManager.GetString("SendToFriends", resourceCulture);
            }
        }
    }
}
