//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class News {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal News() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.News", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * براي ثبت يا ويرايش اطلاعات، پرکردن موارد ستاره دار الزامي است..
        /// </summary>
        internal static string AlertStar {
            get {
                return ResourceManager.GetString("AlertStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعيت اين خبر را چگونه ارزيابي مي کنيد؟.
        /// </summary>
        internal static string AlertStatus {
            get {
                return ResourceManager.GetString("AlertStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام گروه ها.
        /// </summary>
        internal static string AllGroups {
            get {
                return ResourceManager.GetString("AllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرشيو.
        /// </summary>
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلی.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان و کليدواژه ها.
        /// </summary>
        internal static string CaptionAndKeywords {
            get {
                return ResourceManager.GetString("CaptionAndKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان خبر.
        /// </summary>
        internal static string CaptionNews {
            get {
                return ResourceManager.GetString("CaptionNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان يا کليدواژه ها.
        /// </summary>
        internal static string CaptionOrKeyWords {
            get {
                return ResourceManager.GetString("CaptionOrKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر ترتیب خبر.
        /// </summary>
        internal static string ChangeOrderly {
            get {
                return ResourceManager.GetString("ChangeOrderly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با انتخاب هريک از گروهها، اخبار 
        ///																مربوط به آن گروه را مشاهده خواهيد کرد. براي بازگشت به حالت اوليه کليد &quot;نمايش 
        ///																همگي&quot; را فشار دهيد..
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاييد شده.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار انتخاب شده و تصاوير آنها حذف خواهند شد! آيا مطمئن هستيد؟.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين گروه حذف خواهد شد! در صورتي که خبري متعلق به اين گروه وجود داشته باشد از حذف گروه جلوگيري مي شود. آيا مطمئن هستيد؟.
        /// </summary>
        internal static string ConfirmDeleteGroup {
            get {
                return ResourceManager.GetString("ConfirmDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين تصوير حذف خواهد شد! آيا مطمئن هستيد؟.
        /// </summary>
        internal static string ConfirmDeleteImage {
            get {
                return ResourceManager.GetString("ConfirmDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين خبر و تصاوير مربوط به آن حذف خواهند شد! آيا مطمئن هستيد؟.
        /// </summary>
        internal static string ConfirmDeleteNewsAndImage {
            get {
                return ResourceManager.GetString("ConfirmDeleteNewsAndImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار انتخاب شده ،گروه خبری آنها  تغییرخواهند کرد! آيا مطمئن هستيد؟.
        /// </summary>
        internal static string ConfirmEditBatch {
            get {
                return ResourceManager.GetString("ConfirmEditBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صحت خبر را تاييد مي کنم. خبر در مدت زمان تعيين شده در سامانه نمايش داده شود..
        /// </summary>
        internal static string ConfirmNewsForShowInPortal {
            get {
                return ResourceManager.GetString("ConfirmNewsForShowInPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين خبر تاييد شده است و در سامانه نمايش داده مي شود..
        /// </summary>
        internal static string ConfirmNewsinPortal {
            get {
                return ResourceManager.GetString("ConfirmNewsinPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايجاد کننده.
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت اطلاعات.
        /// </summary>
        internal static string DataManagment {
            get {
                return ResourceManager.GetString("DataManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ پايان نمايش.
        /// </summary>
        internal static string DateEndShow {
            get {
                return ResourceManager.GetString("DateEndShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ مخابره.
        /// </summary>
        internal static string DateNews {
            get {
                return ResourceManager.GetString("DateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ شروع نمايش.
        /// </summary>
        internal static string DateStarShow {
            get {
                return ResourceManager.GetString("DateStarShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف اخبار انتخاب شده.
        /// </summary>
        internal static string DeleteSelectNews {
            get {
                return ResourceManager.GetString("DeleteSelectNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضيحات.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويرايش.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال تغييرات.
        /// </summary>
        internal static string EditData {
            get {
                return ResourceManager.GetString("EditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اين گروه وجود ندارد. احتمالا در اين گروه اخباري وارد شده است. براي حذف گروه لازم است ابتدااخبار مربوط به آن حذف يا به گروه ديگري منتقل شوند..
        /// </summary>
        internal static string ErrorDeleteGroup {
            get {
                return ResourceManager.GetString("ErrorDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اين تصوير وجود ندارد!.
        /// </summary>
        internal static string ErrorDeleteImage {
            get {
                return ResourceManager.GetString("ErrorDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اين خبر وجود ندارد!.
        /// </summary>
        internal static string ErrorDeleteNews {
            get {
                return ResourceManager.GetString("ErrorDeleteNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه تکراری است.
        /// </summary>
        internal static string ErrorDuplicateInsertData {
            get {
                return ResourceManager.GetString("ErrorDuplicateInsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه تکراری می باشد .
        /// </summary>
        internal static string ErrorDuplicateName {
            get {
                return ResourceManager.GetString("ErrorDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در ويرايش عنوان تصوير مشکل پيش آمده است. لطفا دوباره سعي کنيد..
        /// </summary>
        internal static string ErrorEditCaptionImage {
            get {
                return ResourceManager.GetString("ErrorEditCaptionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در روند ويرايش اطلاعات مشکلي به وجود آمده است. لطفا دوباره سعي کنيد..
        /// </summary>
        internal static string ErrorEditData {
            get {
                return ResourceManager.GetString("ErrorEditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در ويرايش تصوير مشکلي به وجود آمده است. لطفا دوباره سعي کنيد..
        /// </summary>
        internal static string ErrorEditImage {
            get {
                return ResourceManager.GetString("ErrorEditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ويرايش اين اطلاعات وجود ندارد. احتمالا تاريخهاي مربوط به آن را درست وارد نکرده ايد. لطفا دوباره سعي کنيد..
        /// </summary>
        internal static string ErrorEditNewsForDate {
            get {
                return ResourceManager.GetString("ErrorEditNewsForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان یا کلمه کلیدی نمی تواند خالی باشد.
        /// </summary>
        internal static string ErrorEmptyBox {
            get {
                return ResourceManager.GetString("ErrorEmptyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در درج اطلاعات مشکلي به وجود آمده است. لطفا دوباره سعي کنيد..
        /// </summary>
        internal static string ErrorInsertData {
            get {
                return ResourceManager.GetString("ErrorInsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در ثبت اطلاعات مشکلي پيش آمده است! لطفا دوباره سعي کنيد..
        /// </summary>
        internal static string ErrorInsertDataTryAgin {
            get {
                return ResourceManager.GetString("ErrorInsertDataTryAgin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to براي ثبت يک تصوير مي بايست آن را وارد کنيد!.
        /// </summary>
        internal static string ErrorInsertImage {
            get {
                return ResourceManager.GetString("ErrorInsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت اين خبر وجود ندارد. احتمالا تاريخهاي مربوط به آن را درست وارد نکرده ايد. لطفا دوباره سعي کنيد..
        /// </summary>
        internal static string ErrorInsertNewsForDate {
            get {
                return ResourceManager.GetString("ErrorInsertNewsForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه تصوير مي بايست حداکثر 25 پيکسل باشد!.
        /// </summary>
        internal static string ErrorSizeImage {
            get {
                return ResourceManager.GetString("ErrorSizeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه تصوير مي بايست حداکثر 200 کيلوبايت باشد..
        /// </summary>
        internal static string ErrorSizePic {
            get {
                return ResourceManager.GetString("ErrorSizePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از مجموع.
        /// </summary>
        internal static string FromSum {
            get {
                return ResourceManager.GetString("FromSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت گروهها.
        /// </summary>
        internal static string GroupManagment {
            get {
                return ResourceManager.GetString("GroupManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه خبري.
        /// </summary>
        internal static string GroupNews {
            get {
                return ResourceManager.GetString("GroupNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت گروههاي خبري.
        /// </summary>
        internal static string GroupNewsManagment {
            get {
                return ResourceManager.GetString("GroupNewsManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت گروههاي خبري - برنامه .
        /// </summary>
        internal static string GroupNewsProgramManagment {
            get {
                return ResourceManager.GetString("GroupNewsProgramManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصوير.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصاوير مربوط به .
        /// </summary>
        internal static string ImagesFor {
            get {
                return ResourceManager.GetString("ImagesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار مهم.
        /// </summary>
        internal static string ImportantNews {
            get {
                return ResourceManager.GetString("ImportantNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين تصوير را براي خبر، درست نمي دانيد؟ اطلاعات مربوط به آن را در اين محل ويرايش کنيد. اگر تصوير جديدي انتخاب ننماييد، همان تصوير پيشين درنظر گرفته خواهد شد.
        /// </summary>
        internal static string IncorrectImageForNews {
            get {
                return ResourceManager.GetString("IncorrectImageForNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات.
        /// </summary>
        internal static string InsertData {
            get {
                return ResourceManager.GetString("InsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت تصوير.
        /// </summary>
        internal static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن اطلاعات جديد.
        /// </summary>
        internal static string InsertNewData {
            get {
                return ResourceManager.GetString("InsertNewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کليدواژه ها.
        /// </summary>
        internal static string KeyWords {
            get {
                return ResourceManager.GetString("KeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مورد نظر شما با موفقيت ويرايش گرديد..
        /// </summary>
        internal static string MessageEditData {
            get {
                return ResourceManager.GetString("MessageEditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مورد نظر شما با موفقيت ثبت گرديد..
        /// </summary>
        internal static string MessageInsertData {
            get {
                return ResourceManager.GetString("MessageInsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال به گروه.
        /// </summary>
        internal static string MoveGroup {
            get {
                return ResourceManager.GetString("MoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای افزودن خبر باید به مدیریت وارد شوید.
        /// </summary>
        internal static string NeedLogIn {
            get {
                return ResourceManager.GetString("NeedLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه جدید.
        /// </summary>
        internal static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرشيو اخبار.
        /// </summary>
        internal static string NewsArchive {
            get {
                return ResourceManager.GetString("NewsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف خبر.
        /// </summary>
        internal static string NewsDelete {
            get {
                return ResourceManager.GetString("NewsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئيات اخبار.
        /// </summary>
        internal static string NewsDetail {
            get {
                return ResourceManager.GetString("NewsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش خبر.
        /// </summary>
        internal static string NewsEdit {
            get {
                return ResourceManager.GetString("NewsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصاویر مربوط به خبر.
        /// </summary>
        internal static string NewsImagesHelpText {
            get {
                return ResourceManager.GetString("NewsImagesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبر مهم است و در قسمت اخبار مهم نمايش داده مي شود.
        /// </summary>
        internal static string NewsImportantShow {
            get {
                return ResourceManager.GetString("NewsImportantShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت اخبار.
        /// </summary>
        internal static string NewsManagment {
            get {
                return ResourceManager.GetString("NewsManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت  اخبار - برنامه .
        /// </summary>
        internal static string NewsManagmentProgram {
            get {
                return ResourceManager.GetString("NewsManagmentProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبر جديد.
        /// </summary>
        internal static string NewsNew {
            get {
                return ResourceManager.GetString("NewsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبر برگزيده است و به عنوان اولين خبر نمايش داده مي شود.
        /// </summary>
        internal static string NewsSelectOneShow {
            get {
                return ResourceManager.GetString("NewsSelectOneShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاصه خبر.
        /// </summary>
        internal static string NewsSummary {
            get {
                return ResourceManager.GetString("NewsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعدی.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبر مهم نيست.
        /// </summary>
        internal static string noImportantNews {
            get {
                return ResourceManager.GetString("noImportantNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این صفحه برای نمایش خبر است ولی خبری برای نمایش به آن ارسال نشده است..
        /// </summary>
        internal static string NoNewsMessage {
            get {
                return ResourceManager.GetString("NoNewsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسمبلی ارسال نظرات موجود نمی باشد.
        /// </summary>
        internal static string NoReviewDLL {
            get {
                return ResourceManager.GetString("NoReviewDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبر برگزيده نيست.
        /// </summary>
        internal static string noSelectNews {
            get {
                return ResourceManager.GetString("noSelectNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسمبلی ارسال ایمیل موجود نمی باشد.
        /// </summary>
        internal static string NoSendMailDLL {
            get {
                return ResourceManager.GetString("NoSendMailDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاييد نشده.
        /// </summary>
        internal static string NotConfirm {
            get {
                return ResourceManager.GetString("NotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صحت خبر را تاييد نمي کنم..
        /// </summary>
        internal static string NotConfirmCorrectNews {
            get {
                return ResourceManager.GetString("NotConfirmCorrectNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اين خبر تاييد نشده است..
        /// </summary>
        internal static string NotConfirmNews {
            get {
                return ResourceManager.GetString("NotConfirmNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دفعات مشاهده.
        /// </summary>
        internal static string NoViewTime {
            get {
                return ResourceManager.GetString("NoViewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام موارد اختياري مي باشند..
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب خبر.
        /// </summary>
        internal static string OrderlyNews {
            get {
                return ResourceManager.GetString("OrderlyNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصوير ديگري مد نظر شماست؟ آن را در اينجا وارد نماييد..
        /// </summary>
        internal static string OtherImage {
            get {
                return ResourceManager.GetString("OtherImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصاوير ديگر.
        /// </summary>
        internal static string OtherImages {
            get {
                return ResourceManager.GetString("OtherImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر اخبار.
        /// </summary>
        internal static string OtherNews {
            get {
                return ResourceManager.GetString("OtherNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرگروه.
        /// </summary>
        internal static string ParentGroup {
            get {
                return ResourceManager.GetString("ParentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک گروه نمی تواند سر گروه خودش باشد..
        /// </summary>
        internal static string ParentUpdateError {
            get {
                return ResourceManager.GetString("ParentUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر.
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا گروه خبر را مشخص کنيد..
        /// </summary>
        internal static string PlzSelectGroupNews {
            get {
                return ResourceManager.GetString("PlzSelectGroupNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه چاپی.
        /// </summary>
        internal static string PrintableVersion {
            get {
                return ResourceManager.GetString("PrintableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادامه مطلب ».
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نظر.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رديف.
        /// </summary>
        internal static string RowId {
            get {
                return ResourceManager.GetString("RowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبر برگزيده.
        /// </summary>
        internal static string SelectNews {
            get {
                return ResourceManager.GetString("SelectNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ارسال مطلب به بيش ازيک آدرس، آنها را با , از هم جدا کنيد. برای مثال.
        /// </summary>
        internal static string SendToFriendMessage {
            get {
                return ResourceManager.GetString("SendToFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال به دوستان.
        /// </summary>
        internal static string SendToFriends {
            get {
                return ResourceManager.GetString("SendToFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمايش همگي.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش تصویر.
        /// </summary>
        internal static string showimage {
            get {
                return ResourceManager.GetString("showimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمايش مطلب.
        /// </summary>
        internal static string ShowNews {
            get {
                return ResourceManager.GetString("ShowNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعيت.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعيت خبر.
        /// </summary>
        internal static string StatusNews {
            get {
                return ResourceManager.GetString("StatusNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه ای که برای نمایش جزئیات وارد کرده اید، وجود ندارد.
        /// </summary>
        internal static string TabIdErrorMessage {
            get {
                return ResourceManager.GetString("TabIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  بار.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال نمایش به پایین.
        /// </summary>
        internal static string TransferShowingToDown {
            get {
                return ResourceManager.GetString("TransferShowingToDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال نمایش به بالا.
        /// </summary>
        internal static string TransferShowingToUp {
            get {
                return ResourceManager.GetString("TransferShowingToUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويرايش اطلاعات.
        /// </summary>
        internal static string UpdateData {
            get {
                return ResourceManager.GetString("UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مربوط به تصوير را مي توانيد در اينجا ويرايش نماييد. اگر در محل مربوط به تصوير، اطلاعاتي وارد ننماييد، همان تصوير پيشين براي شما در نظر گرفته خواهد شد..
        /// </summary>
        internal static string UpdateImage {
            get {
                return ResourceManager.GetString("UpdateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان خبر را وارد کنيد.
        /// </summary>
        internal static string ValidationCaption {
            get {
                return ResourceManager.GetString("ValidationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه را وارد کنيد.
        /// </summary>
        internal static string ValidationGroupName {
            get {
                return ResourceManager.GetString("ValidationGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه خبر را وارد کنيد.
        /// </summary>
        internal static string ValidationGroupNews {
            get {
                return ResourceManager.GetString("ValidationGroupNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
